android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, android/app/build.gradle, android/build.gradle, android/gradle.properties, lib/screens/buyer/login_screen.dart
- Configures Firebase dependencies, including Analytics, Auth, and Firestore, in the Android build.
- Upgrades Gradle and Kotlin versions for compatibility with the latest Flutter recommendations.
- Adjusts Android build properties, including target SDK version and manifest placeholders for Firebase integration.
- Handles null values for user data (email, name, photo URL) in the login screen to prevent runtime errors.
Relates to Firebase setup and improves app stability.
=> Updates Android build for Firebase integration and improves null handling in login screen

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/main.dart, lib/providers/auth_provider.dart, lib/screens/buyer/forgot_password_screen.dart, lib/screens/buyer/login_screen.dart
Introduces forgot password functionality to improve user experience:
- Implements a forgot password screen with email validation and user feedback
- Enhances the authentication provider with password reset support and logging
- Updates UI elements for better usability and error handling
- Modifies login flow to integrate forgot password navigation
Provides users with a secure and intuitive way to reset their passwords via email.
=> Adds forgot password functionality with enhanced UI and validation

devtools_options.yaml, lib/main.dart, lib/models/user_profile_model.dart, lib/providers/user_registration_provider.dart, lib/screens/buyer/profile_screen.dart, lib/screens/buyer/register_info_screen.dart, lib/screens/buyer/verify_email_screen.dart, pubspec.lock, pubspec.yaml
Introduces features for improved user registration and profile handling:
- Adds user registration provider for managing registration and verification flows
- Implements user profile model to structure user data
- Enhances profile screen with data completeness checks and dynamic rendering
- Integrates email verification with navigation based on profile completeness
- Adds registration info screen for collecting additional user details
Improves overall user authentication and onboarding experience.
Fixes #123
=> Enhances user registration and profile management

android/app/.cxx/Debug/4k4o4663/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4k4o4663/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4k4o4663/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4k4o4663/x86_64/configure_fingerprint.bin, lib/providers/cart_providers.dart, lib/providers/wishlist_providers.dart, lib/screens/buyer/main_home_screen.dart, lib/screens/buyer/product_details_screen.dart, lib/utils/snackbar_helper.dart
-added utils folder for reusable snackbar
=> with product details

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, android/app/build.gradle, lib/main.dart, lib/screens/buyer/login_screen.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml
- Adds Firebase App Check activation to improve app security.
- Enhances Google Sign-In flow to handle profile checks for new and existing users.
- Improves error handling with user-friendly messages during sign-in.
- Updates dependencies to include Firebase App Check.
- Refines build.gradle for Firebase services integration.
These changes enhance app security and user experience during authentication.
Fixes #123
=> Integrates Firebase App Check and enhances Google Sign-In flow

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/main.dart, lib/providers/edit_profile_provider.dart, lib/providers/user_profile_provider.dart, lib/screens/buyer/edit_profile_screen.dart, lib/screens/buyer/home_screen.dart, lib/screens/buyer/profile_screen.dart
Introduces the ability for users to edit their profile information:
- Adds a centralized user profile provider for data management
- Implements an edit profile provider to handle profile updates and image uploads
- Integrates profile editing into the UI, including form validation and photo upload options
- Updates home and profile screens to reflect changes dynamically
Enhances user experience by allowing real-time profile updates and synchronization.
Fixes #789
=> Adds edit profile functionality with provider integration

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/screens/buyer/login_screen.dart
Improves the Google Sign-In process to enhance user experience:
- Clears cached credentials by signing out before initiating sign-in.
- Configures Google Sign-In to force account selection for better control.
- Adds `forceCodeForRefreshToken` to ensure token refresh during sign-in.
These updates address potential issues with cached credentials and provide a more reliable authentication flow.
Relates to #feat
=> Enhances Google Sign-In by clearing cache and enforcing account selection

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, android/app/src/main/AndroidManifest.xml, ios/Runner/Info.plist, lib/providers/auth_provider.dart, lib/screens/buyer/change_password_screen.dart, lib/screens/buyer/profile_screen.dart, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
Implements a feature to allow users to change their passwords, including validation and error handling:
- Updates the profile screen with a 'Change Password' menu item
- Implements detailed password change logic in the authentication provider
- Adds a dedicated UI for password updates with form validation and error feedback
Enhances URL handling capabilities:
- Updates AndroidManifest.xml and Info.plist to support URL schemes
- Integrates the URL launcher plugin for cross-platform support
Fixes #789
=> Adds change password functionality and URL handling support

android/app/.cxx/Debug/4k4o4663/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4k4o4663/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4k4o4663/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4k4o4663/x86_64/configure_fingerprint.bin, lib/screens/buyer/cart_screen.dart, lib/screens/buyer/home_screen.dart, lib/screens/buyer/wishlist_screen.dart, lib/widgets/not_logged_in.dart
-improved guest handling
-added not_logged_in file
=> improved guest handling

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/providers/seller_registration_provider.dart, lib/screens/buyer/profile_screen.dart, lib/screens/seller/seller_dashboard_screen.dart
- Introduces a seller dashboard screen with key metrics and quick actions for sellers to manage their store.
- Implements a seller approval status check in the profile screen to dynamically update the seller-related menu options.
- Refactors profile screen menu items for improved usability and readability.
- Enhances user flow by allowing approved sellers to access the dashboard directly and unapproved sellers to proceed with registration or verification.
Fixes #789
=> Adds seller dashboard and integrates seller approval check

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/main.dart, lib/models/product_model.dart, lib/providers/product_provider.dart, lib/screens/buyer/main_home_screen.dart, lib/screens/seller/product_form_screen.dart, lib/screens/seller/product_listing_screen.dart, lib/screens/seller/seller_dashboard_screen.dart, pubspec.lock, pubspec.yaml
Introduces comprehensive product management functionality:
- Implements add, update, delete, and listing operations for products
- Updates product model to handle legacy data and support enhanced category management
- Adds provider for product-specific operations with Firebase integration
Improves user experience:
- Enhances product form with subcategory selection and image management
- Updates UI for product listing, filtering, and dashboard integration
Fixes issues with backward compatibility and streamlines category handling.
=> Enhances product management and category features

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/screens/checkout/shipping_address_form.dart, lib/utils/address_mapper.dart
Enhances the shipping address form with the following updates:
- Adds functionality to load and display saved addresses
- Enables users to select a default or new address for shipping
- Introduces address mapping utility for model conversions
- Refactors UI to improve usability and align with modern design patterns
Streamlines the checkout process by allowing address reuse.
=> Implements saved address selection in shipping form

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/screens/seller/seller_processing_screen.dart, pubspec.lock
Enhances the seller processing screen with the following updates:
- Refactors the widget structure into smaller, reusable methods for better readability.
- Improves form validation logic and messages to enhance user experience.
- Updates UI feedback for image uploads with clearer prompts and validation.
- Adds section headers and descriptions for better organization and clarity.
- Removes redundant context references and comments for cleaner code.
- Updates styling for consistency and improved visual hierarchy.
Also updates dependencies in the `pubspec.lock` file to their latest compatible versions.
Relates to improved user experience and code maintainability goals.
=> Refactors seller processing screen for improved UX and maintainability

android/app/.cxx/Debug/4k4o4663/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4k4o4663/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4k4o4663/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4k4o4663/x86_64/configure_fingerprint.bin, lib/main.dart, lib/providers/seller_orders_provider.dart, lib/screens/seller/order_listing_screen.dart, pubspec.yaml
- Added SellerOrdersProvider to manage fetching and updating seller orders.
- Integrated SellerOrdersProvider into the SellerOrdersScreen for displaying orders.
- Updated UI to show order details and allow status updates.
- Refactored order fetching logic to use the new provider.
- Enhanced order status display with color coding.
- Added snackbar feedback for order status updates.
- Updated pubspec.yaml to include necessary dependencies.
=> feat: Implement seller orders management

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/screens/buyer/register_screen.dart
Enhances the user registration screen by introducing password validation requirements and real-time feedback.
- Added validation for password strength, including checks for:  
- Minimum length of 8 characters  
- At least one uppercase letter  
- At least one lowercase letter  
- At least one number  
- Implemented dynamic feedback to inform users of unmet password requirements.  
- Updated UI to display password criteria when the password field is focused or non-empty.
- Improves user experience by guiding users to create strong passwords.  
- Enhances security by enforcing stricter password policies.  
- Provides immediate feedback, reducing failed registration attempts.
The requirement for special characters was removed as per the second commit.
=> Add password validation and feedback in registration screen

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/screens/seller/product_listing_screen.dart
- Improves the product listing screen UI by adopting consistent and modern button designs using `ElevatedButton` with custom styles.  
- Updates the floating action button to an extended version for better usability and aesthetic consistency.  
- Refines filter chip designs with improved typography, colors, and selectable states to enhance user experience.  
- Adjusts padding, shapes, and elevation across components for better accessibility and visual appeal.  
These changes align with the goal of providing a more polished and user-friendly interface for managing product listings while maintaining consistency with the app's overall design language.
=> Enhance product listing UI with updated button and chip styles

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/screens/buyer/login_screen.dart, lib/screens/seller/seller_dashboard_screen.dart, lib/screens/seller/seller_profile_screen.dart
Introduces seller-focused features, including role-based navigation, seller profile management, and enhanced seller dashboard functionalities.
- **Login Flow:**
- Implements seller status check during user login.
- Adds navigation logic for directing sellers to a dedicated dashboard if preferred.
- **Seller Profile Management:**
- Adds a comprehensive seller profile screen with:
- Profile image upload functionality.
- Editable business information, including business hours and payment details.
- **Seller Dashboard Enhancements:**
- Introduces a profile section with verification status.
- Adds support for managing business hours and payment information directly from the dashboard.
- Enables tailored experiences for sellers by providing role-based navigation.
- Offers sellers tools to …
=> Add seller profile management and role-based navigation

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/models/address_model.dart, lib/providers/address_provider.dart, lib/screens/buyer/add_address_screen.dart, lib/screens/buyer/saved_addresses_screen.dart, lib/utils/address_mapper.dart
Introduces a `userId` field to the `Address` model to improve multi-user address management. Updates related functionalities and logic to handle this change effectively.
- **Enhancements to Address Model**:  
- Added `userId` field to associate addresses with specific users.
- Updated methods for serialization/deserialization to include `userId`.
- **Provider Refactor**:  
- Adjusted address loading logic to prioritize user-specific subcollections in Firestore.
- Added fallback mechanism for older implementations using global collections.
- Improved error handling for authentication and permission issues.
- **UI Improvements**:  
- Updated error messages and retry functionality in the saved addresses screen to handle permission errors.
- Ensured proper userId initialization when adding or …
=> Add userId to Address model and refactor address management

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/models/product_model.dart, lib/screens/buyer/home_screen.dart, lib/screens/buyer/product_details_screen.dart, lib/screens/buyer/seller_public_profile_screen.dart, lib/screens/seller/seller_dashboard_screen.dart, lib/screens/seller/seller_profile_screen.dart, lib/screens/seller/store_policies_preview_screen.dart
This pull request introduces significant improvements to the seller dashboard, profile screens, and product details functionality. The changes include UI enhancements, additional features, and improved validation to provide a better user experience for sellers and buyers.
- **Seller Dashboard**:
- Added profile completeness checks with progress indicators to encourage sellers to update missing information.
- Implemented validation and visual feedback for essential fields like phone, email, and website.
- **Seller Profile Screen**:
- Introduced a new "Store Policies" tab, allowing sellers to define return, shipping, and terms & conditions policies.
- Added a preview feature to review store policies before saving.
- Improved business hours input with a user-friendly UI for setting open and …
=> Enhance seller dashboard, profile, and product details

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/screens/seller/product_form_screen.dart, pubspec.lock
Introduces improvements to the product form UI, focusing on better brand selection, pricing validation, and overall user experience.
- **Vintage Brand Selection**: Added a dropdown with a curated list of vintage brands, dynamic filtering, and support for custom brand input.
- **SKU Generation**: Implemented automatic SKU generation based on brand and category.
- **Pricing Validation**: Enhanced validation to ensure selling price exceeds cost price, with visual feedback for profit margins.
- **Discount Calculator**: Added a tool to calculate sale prices with percentage-based discounts.
- **UI Improvements**: Refined layout and organization of form fields for better usability and accessibility.
- **Dependency Updates**: Updated `pubspec.lock` to ensure compatibility with the latest versions …
=> Enhance product form with vintage brand selection and pricing validation

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/screens/seller/inventory_dashboard_screen.dart, lib/screens/seller/seller_dashboard_screen.dart
- Refines the seller dashboard UI for better usability and visual consistency.
- Adjusts navigation to directly load the Inventory Dashboard.
- Preloads product data when the dashboard opens to improve data availability.
- Removed unused "Add Product" buttons to declutter the UI.
- Updated layout elements to reduce padding, adjust font sizes, and enhance responsiveness.
- Modified navigation to route to the Inventory Dashboard instead of the product listing screen.
- Added automatic loading of product data during dashboard initialization to ensure readiness.
- Provides a cleaner and more intuitive user experience.
- Enhances layout consistency across the dashboard.
- Reduces manual steps for sellers by preloading product data.
Relates to improving seller dashboard usability and data …
=> Update seller dashboard UI and navigation; preload products

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/screens/buyer/payment_methods_screen.dart, lib/screens/buyer/profile_screen.dart, lib/screens/checkout/payment_method_form.dart, lib/widgets/custom_bottomnav.dart
Introduces a comprehensive payment methods management system, enabling users to add, edit, delete, and manage saved payment methods. Also adds support for PayPal with email validation and enhances the user interface for a seamless experience.
- Implements a dedicated screen for managing payment methods with Firebase integration.
- Adds PayPal as a supported payment type, including email validation.
- Enhances the payment method form with saved method integration and loading indicators.
- Updates navigation to include access to the payment methods screen.
- Improves UI/UX with better alignment, spacing, and consistent design patterns.
- Supports setting default payment methods and error handling for common actions.
- Enables users to manage payment methods conveniently within the app.
- …
=> Add payment methods management with PayPal support and UI improvements

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/data/help_data.dart, lib/models/help_models.dart, lib/screens/buyer/help_center_screen.dart, lib/screens/buyer/help_detail_screen.dart, lib/screens/buyer/notification_preferences_screen.dart, lib/screens/buyer/profile_screen.dart, pubspec.yaml
- Introduces a comprehensive Help Center feature to assist users with app guidance and troubleshooting.
- Improves the Notification Preferences screen with enhanced error handling, user feedback, and widget state checks.
- Implements Help Center and Help Detail screens with a user-friendly interface.
- Adds detailed help categories, articles, and step-by-step guides for various app features.
- Includes search functionality to allow users to find relevant help topics easily.
- Provides support options like live chat, email, and phone integration for further assistance.
- Adds robust error handling and user feedback mechanisms to improve reliability.
- Ensures safe widget state checks (`mounted` verification) to prevent runtime errors.
- Enhances UI feedback with success/error messages and …
=> Add Help Center and enhance notification preferences handling

README.md, android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin
Enhances the README.md to provide a comprehensive overview of the Haul app, including its features, tech stack, architecture, and setup instructions. 
- Adds a detailed description of the app's purpose and functionality.
- Introduces sections for buyer and seller features, core features, and the app's tech stack.
- Includes setup instructions for cloning, installing dependencies, and configuring Firebase.
- Provides details on testing, deployment, and contributing guidelines.
- Removes outdated screenshots and empty sections for clarity.
These updates aim to improve developer onboarding and provide a clearer understanding of the app's capabilities and structure.
=> Revamp README.md with detailed app overview and setup guide

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/helpers/responsive_helper.dart, lib/models/wishlist_model.dart, lib/providers/seller_registration_provider.dart, lib/providers/wishlist_providers.dart, lib/screens/buyer/search_screen.dart, lib/screens/buyer/wishlist_screen.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
This pull request introduces significant changes across multiple files, focusing on enhancing responsiveness, improving data models, and updating structured logging for Android builds. Below is a summary of the most important changes:
* Added a new `ResponsiveHelper` class in `lib/helpers/responsive_helper.dart` to manage screen breakpoints, grid configurations, font sizes, padding, and other UI-related properties dynamically based on screen size. This centralizes responsive logic for better maintainability.
* Updated `WishlistModel` in `lib/models/wishlist_model.dart` to include additional fields such as `id`, `sellerId`, `sellerName`, `brand`, `condition`, `size`, `isOnSale`, `salePrice`, and `originalStock`. Enhanced methods like `toMap` and `fromMap` to handle these new fields. …
=> Enhancement Wishlist Feature

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/providers/checkout_provider.dart, lib/screens/buyer/package_tracking_screen.dart, lib/screens/seller/order_detail_screen.dart, lib/screens/seller/order_listing_screen.dart, lib/screens/seller/seller_dashboard_screen.dart, pubspec.lock
- **Order Detail and Listing Screens**  
- Improved data handling and debugging for better performance and troubleshooting.  
- Added dynamic calculation of order totals and detailed error handling for product images.  
- Enhanced shipping, payment, and item data extraction with robust field mapping.  
- **Seller Dashboard**  
- Introduced real-time total orders count and sales metrics updates.  
- Enhanced analytics loading with fallback strategies and improved product data handling.  
- **Package Tracking and Navigation**  
- Improved order status visibility with redesigned status indicators and conditional UI updates.  
- **Refactoring and Utilities**  
- Added helper methods for consistent data extraction across screens.  
- Updated dependency versions in `pubspec.lock` for …
=> Enhance order management and seller dashboard functionality

android/app/.cxx/Debug/4z3f3b5t/arm64-v8a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/armeabi-v7a/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86/configure_fingerprint.bin, android/app/.cxx/Debug/4z3f3b5t/x86_64/configure_fingerprint.bin, lib/screens/buyer/privacy_settings_screen.dart, lib/screens/buyer/profile_screen.dart, lib/screens/buyer/return_status_screen.dart, lib/screens/buyer/start_return_screen.dart
Introduces privacy settings management and return request handling for improved buyer experience. Integrates these functionalities into the profile section with seamless navigation and Firestore backend support.
- **Privacy Settings:**
- Added a dedicated screen for managing privacy preferences.
- Enabled features such as toggling data collection, marketing communication, and profile visibility.
- Integrated Firestore for saving and loading user preferences.
- Enhanced UI with feedback messages and intuitive layouts.
- **Return Management:**
- Implemented screens for starting return requests and tracking return statuses.
- Provided filtering options to view returns by status.
- Enabled item and order selection for initiating returns.
- Integrated Firestore for fetching and submitting …
=> Add privacy settings and return management features
